name: test

on:
  push:
    branches: ['*']


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19']
    steps:
      - uses: actions/checkout@v3
      - name: set up go version ${{ matrix.go }}
        uses:  actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: units test for go ${{ matrix.go}}
        run: go test ./...
          

